"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const All_1 = require("./All");
const Any_1 = require("./Any");
const Compare_1 = require("./Compare");
const Count_1 = require("./Count");
const Difference_1 = require("./Difference");
const Drop_1 = require("./Drop");
const Flatten_1 = require("./Flatten");
const Gather_1 = require("./Gather");
const Group_1 = require("./Group");
const Pull_1 = require("./Pull");
const Reduce_1 = require("./Reduce");
const Remove_1 = require("./Remove");
const Unique_1 = require("./Unique");
const index_1 = require("../Type/index");
function arrayExpansion() {
    Array.prototype.all = All_1.all;
    Array.prototype.any = Any_1.any;
    Array.prototype.max = Compare_1.max;
    Array.prototype.min = Compare_1.min;
    Array.prototype.count = Count_1.count;
    Array.prototype.difference = Difference_1.difference;
    Array.prototype.differenceBy = Difference_1.differenceBy;
    Array.prototype.drop = Drop_1.drop;
    Array.prototype.dropRight = Drop_1.dropRight;
    Array.prototype.flatten = Flatten_1.flatten;
    Array.prototype.intersection = Gather_1.intersection;
    Array.prototype.union = Gather_1.union;
    Array.prototype.groupBy = Group_1.groupBy;
    Array.prototype.pull = Pull_1.pull;
    Array.prototype.pullBy = Pull_1.pullBy;
    Array.prototype.reduceFilter = Reduce_1.reduceFilter;
    Array.prototype.remove = Remove_1.remove;
    Array.prototype.unique = Unique_1.unique;
    Array.prototype.isEmpty = index_1.isEmpty;
    Array.prototype.isNull = index_1.isNull;
    Array.prototype.isValid = index_1.isValid;
}
exports.arrayExpansion = arrayExpansion;
;
